### ISSUE TITLE
Project Submission for the Kanban

### ISSUE THREAD

**Issue by Carshy** [Carshy/catalog-ruby-project#34]
In the current project, we have divided the tasks amongst ourselves in a group of three members (Collins Musoko, Tarek Yosry, and Michael Adetunji). The tasks assigned indicate how we are going to work collaboratively and individually. Collins Musoko is member 1, Tarek Yosry is member 3, then Michael Adetunji is member 3.

Kanban board: https://github.com/Carshy/catalog-ruby-project/projects/1

**Comment by mirouhml** [comment]
Hi @Carshy @tarek102 @Therealadetunji , 

While you made a great effort, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted an issue, that doesn't have a link to your kanban board, please include the link in the issue.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in this thread if something is not 100% clear.

**Comment by GzimAsani** [comment]
### Hello    team      :wave:   
 Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there!
 
 ## Highlights
 * You added the link on the MR description
 * The necessary tasks are created :+1: 

 ## Required Changes 

- [ ] Number of points from tasks for each of the members, as you can see there is a big difference with the last one, so please re-arrange or re-evaluate the tasks in order to have not have more than 5 points difference 
[Carshy](https://github.com/Carshy) -  21 Points
[Therealadetunji](https://github.com/Therealadetunji) - 18 Points
[Therealadetunji](https://github.com/Therealadetunji) - 11 Points






 ## Optional suggestions
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding! clapclapclap
 
 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
 
 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Carshy** [comment]
We reviewed our points and made adjustments as requested: Collins Musoko(20 pts), Tarek Yosry (18 pts), Michael Adetunji (18 pts). @GzimAsani thanks for your review it was really helpful

**Comment by prolajumokeoni** [comment]
Hi @Team

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
## Highlights
- Good setup

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
